sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hSxfwd3qDw0+5Vh10kMpxRRaLrZQMrFFxtCsNXFXMTxjPzT2LMQkF8jsjF9vU39CCVnP8uJtYDhvd1ruIAMu8vz7VxnaFYO8a1866704VD4yG+zpKTso9SA3sRHt1oiN4SFJqTXLLrt4KdwhVXQ+Qwc+2fO1ccqj6ne6B9GHP2NEBCxHvX+QJ8TlkPoABHXpwvCuGCPup8f4JUU+KRr4tI0C/sRVf7Y785NINWA0aIkTNhHeslWXav8jnftJR3lLvsR7HhPLe9wKZPB/RByr/Vu8Tn78XxKezzSCPPh2UpJMTWc15At9otoor03Yjpdyid+OvENb/4b2Br2SumqnniJ75PBNJs9CRtzrTA1et512wgyzjucILyPmffoct0OKF34B4qYEQgbK3pjGCuygLzTev9mURQa16Hy0lo1Iez+An7/wjxLtR4pMuNA9vfZl0SiDSuMnC0/GjQ9KMWacjAV+5m/Y4M6mCSOBrmJmsQ8ujHsbyLaZgvin7TbvBBjkOHNHYZ1jdaq/MDVFPP7agZFlExYjT/pK9Mb03AHMBtj9r07BI2l+BdCCZnFjjerqgvhWeNUOv/bzYSULrGnzsHYZZ8Z+ZJDOfhgqx6xjuOsVV1NTwWtKJpUYCPVIpWDsEqX81MKzlcWbPCuj+w39DG0NoI8sfmd6UfCy0Jt+nwA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Poor-Miss-Finch_3632
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy